artifact_uri: file:///C:/Users/서규혁/OneDrive/바탕 화면/LFD_bitcoin/loggercheckpoint/346992760781701504/4c29ca3869cd4928bbc4ad06f1bcd8ef/artifacts
end_time: 1717831215852
entry_point_name: ''
experiment_id: '346992760781701504'
lifecycle_stage: active
run_id: 4c29ca3869cd4928bbc4ad06f1bcd8ef
run_name: transformer_normal
run_uuid: 4c29ca3869cd4928bbc4ad06f1bcd8ef
source_name: ''
source_type: 4
source_version: ''
start_time: 1717830227465
status: 3
tags: []
user_id: 서규혁
