artifact_uri: file:///C:/Users/서규혁/OneDrive/바탕 화면/LFD_bitcoin/loggercheckpoint/928074780753742447/cc84a1d188564ef5808d767fcb0bafcf/artifacts
end_time: 1717771303521
entry_point_name: ''
experiment_id: '928074780753742447'
lifecycle_stage: active
run_id: cc84a1d188564ef5808d767fcb0bafcf
run_name: hydra_mlflow
run_uuid: cc84a1d188564ef5808d767fcb0bafcf
source_name: ''
source_type: 4
source_version: ''
start_time: 1717771297897
status: 4
tags: []
user_id: 서규혁
