artifact_uri: file:///C:/Users/서규혁/OneDrive/바탕 화면/LFD_bitcoin/loggercheckpoint/346992760781701504/ae8142e6f7da455ca20b3a7fcbaa73ac/artifacts
deleted_time: 1717782850766
end_time: 1717778321002
entry_point_name: ''
experiment_id: '346992760781701504'
lifecycle_stage: deleted
run_id: ae8142e6f7da455ca20b3a7fcbaa73ac
run_name: hydra_mlflow
run_uuid: ae8142e6f7da455ca20b3a7fcbaa73ac
source_name: ''
source_type: 4
source_version: ''
start_time: 1717778315477
status: 4
tags: []
user_id: 서규혁
